// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1477820681433528848),
    name: 'AddressEntity',
    lastPropertyId: const obx_int.IdUid(8, 5199336854907155560),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5622400124530857680),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8082307266984153535),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9157864225720524016),
        name: 'street',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1795896203812707004),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 390058692152350030),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2265260786453945604),
        name: 'zip',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2830698267504522050),
        name: 'instructions',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5199336854907155560),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5334531343012580273),
    name: 'OrderHistoryEntity',
    lastPropertyId: const obx_int.IdUid(6, 3414886064826556343),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4834519910213617738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8073685669669816209),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4050028607632849430),
        name: 'total',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8780638757814632901),
        name: 'itemsCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4972434680091028305),
        name: 'addressLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3414886064826556343),
        name: 'paymentLabel',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 193487142822458394),
    name: 'PaymentMethodEntity',
    lastPropertyId: const obx_int.IdUid(5, 8679616004112684093),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6359280108855887183),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1630571863541724183),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2328391142415605904),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 765011959481417360),
        name: 'details',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8679616004112684093),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2564094772984936264),
    name: 'SettingEntity',
    lastPropertyId: const obx_int.IdUid(3, 1421142607374814391),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 968380527404980896),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7858104027008483821),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8752433055044821374),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1421142607374814391),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6121475857463179970),
    name: 'UserProfileEntity',
    lastPropertyId: const obx_int.IdUid(6, 4979884749638832548),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 801309363517793027),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5589935165303254250),
        name: 'userId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 6951682366237332195),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4764965218960699376),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5326315928537683493),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7563448316660599191),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4979884749638832548),
        name: 'birthDate',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6121475857463179970),
    lastIndexId: const obx_int.IdUid(2, 6951682366237332195),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AddressEntity: obx_int.EntityDefinition<AddressEntity>(
      model: _entities[0],
      toOneRelations: (AddressEntity object) => [],
      toManyRelations: (AddressEntity object) => {},
      getId: (AddressEntity object) => object.id,
      setId: (AddressEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AddressEntity object, fb.Builder fbb) {
        final labelOffset = fbb.writeString(object.label);
        final streetOffset = fbb.writeString(object.street);
        final cityOffset = fbb.writeString(object.city);
        final stateOffset = fbb.writeString(object.state);
        final zipOffset = fbb.writeString(object.zip);
        final instructionsOffset = fbb.writeString(object.instructions);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, labelOffset);
        fbb.addOffset(2, streetOffset);
        fbb.addOffset(3, cityOffset);
        fbb.addOffset(4, stateOffset);
        fbb.addOffset(5, zipOffset);
        fbb.addOffset(6, instructionsOffset);
        fbb.addBool(7, object.isDefault);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final streetParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final stateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final zipParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final instructionsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = AddressEntity(
          id: idParam,
          label: labelParam,
          street: streetParam,
          city: cityParam,
          state: stateParam,
          zip: zipParam,
          instructions: instructionsParam,
          isDefault: isDefaultParam,
        );

        return object;
      },
    ),
    OrderHistoryEntity: obx_int.EntityDefinition<OrderHistoryEntity>(
      model: _entities[1],
      toOneRelations: (OrderHistoryEntity object) => [],
      toManyRelations: (OrderHistoryEntity object) => {},
      getId: (OrderHistoryEntity object) => object.id,
      setId: (OrderHistoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (OrderHistoryEntity object, fb.Builder fbb) {
        final createdAtOffset = fbb.writeString(object.createdAt);
        final addressLabelOffset = fbb.writeString(object.addressLabel);
        final paymentLabelOffset = fbb.writeString(object.paymentLabel);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, createdAtOffset);
        fbb.addFloat64(2, object.total);
        fbb.addInt64(3, object.itemsCount);
        fbb.addOffset(4, addressLabelOffset);
        fbb.addOffset(5, paymentLabelOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final totalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final itemsCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final addressLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final paymentLabelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = OrderHistoryEntity(
          id: idParam,
          createdAt: createdAtParam,
          total: totalParam,
          itemsCount: itemsCountParam,
          addressLabel: addressLabelParam,
          paymentLabel: paymentLabelParam,
        );

        return object;
      },
    ),
    PaymentMethodEntity: obx_int.EntityDefinition<PaymentMethodEntity>(
      model: _entities[2],
      toOneRelations: (PaymentMethodEntity object) => [],
      toManyRelations: (PaymentMethodEntity object) => {},
      getId: (PaymentMethodEntity object) => object.id,
      setId: (PaymentMethodEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PaymentMethodEntity object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final labelOffset = fbb.writeString(object.label);
        final detailsOffset = fbb.writeString(object.details);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, labelOffset);
        fbb.addOffset(3, detailsOffset);
        fbb.addBool(4, object.isDefault);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final detailsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = PaymentMethodEntity(
          id: idParam,
          type: typeParam,
          label: labelParam,
          details: detailsParam,
          isDefault: isDefaultParam,
        );

        return object;
      },
    ),
    SettingEntity: obx_int.EntityDefinition<SettingEntity>(
      model: _entities[3],
      toOneRelations: (SettingEntity object) => [],
      toManyRelations: (SettingEntity object) => {},
      getId: (SettingEntity object) => object.id,
      setId: (SettingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SettingEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = SettingEntity(
          id: idParam,
          key: keyParam,
          value: valueParam,
        );

        return object;
      },
    ),
    UserProfileEntity: obx_int.EntityDefinition<UserProfileEntity>(
      model: _entities[4],
      toOneRelations: (UserProfileEntity object) => [],
      toManyRelations: (UserProfileEntity object) => {},
      getId: (UserProfileEntity object) => object.id,
      setId: (UserProfileEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserProfileEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final birthDateOffset = object.birthDate == null
            ? null
            : fbb.writeString(object.birthDate!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(4, phoneOffset);
        fbb.addOffset(5, birthDateOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final birthDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = UserProfileEntity(
          id: idParam,
          userId: userIdParam,
          name: nameParam,
          email: emailParam,
          phone: phoneParam,
          birthDate: birthDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AddressEntity] entity fields to define ObjectBox queries.
class AddressEntity_ {
  /// See [AddressEntity.id].
  static final id = obx.QueryIntegerProperty<AddressEntity>(
    _entities[0].properties[0],
  );

  /// See [AddressEntity.label].
  static final label = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[1],
  );

  /// See [AddressEntity.street].
  static final street = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[2],
  );

  /// See [AddressEntity.city].
  static final city = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[3],
  );

  /// See [AddressEntity.state].
  static final state = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[4],
  );

  /// See [AddressEntity.zip].
  static final zip = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[5],
  );

  /// See [AddressEntity.instructions].
  static final instructions = obx.QueryStringProperty<AddressEntity>(
    _entities[0].properties[6],
  );

  /// See [AddressEntity.isDefault].
  static final isDefault = obx.QueryBooleanProperty<AddressEntity>(
    _entities[0].properties[7],
  );
}

/// [OrderHistoryEntity] entity fields to define ObjectBox queries.
class OrderHistoryEntity_ {
  /// See [OrderHistoryEntity.id].
  static final id = obx.QueryIntegerProperty<OrderHistoryEntity>(
    _entities[1].properties[0],
  );

  /// See [OrderHistoryEntity.createdAt].
  static final createdAt = obx.QueryStringProperty<OrderHistoryEntity>(
    _entities[1].properties[1],
  );

  /// See [OrderHistoryEntity.total].
  static final total = obx.QueryDoubleProperty<OrderHistoryEntity>(
    _entities[1].properties[2],
  );

  /// See [OrderHistoryEntity.itemsCount].
  static final itemsCount = obx.QueryIntegerProperty<OrderHistoryEntity>(
    _entities[1].properties[3],
  );

  /// See [OrderHistoryEntity.addressLabel].
  static final addressLabel = obx.QueryStringProperty<OrderHistoryEntity>(
    _entities[1].properties[4],
  );

  /// See [OrderHistoryEntity.paymentLabel].
  static final paymentLabel = obx.QueryStringProperty<OrderHistoryEntity>(
    _entities[1].properties[5],
  );
}

/// [PaymentMethodEntity] entity fields to define ObjectBox queries.
class PaymentMethodEntity_ {
  /// See [PaymentMethodEntity.id].
  static final id = obx.QueryIntegerProperty<PaymentMethodEntity>(
    _entities[2].properties[0],
  );

  /// See [PaymentMethodEntity.type].
  static final type = obx.QueryStringProperty<PaymentMethodEntity>(
    _entities[2].properties[1],
  );

  /// See [PaymentMethodEntity.label].
  static final label = obx.QueryStringProperty<PaymentMethodEntity>(
    _entities[2].properties[2],
  );

  /// See [PaymentMethodEntity.details].
  static final details = obx.QueryStringProperty<PaymentMethodEntity>(
    _entities[2].properties[3],
  );

  /// See [PaymentMethodEntity.isDefault].
  static final isDefault = obx.QueryBooleanProperty<PaymentMethodEntity>(
    _entities[2].properties[4],
  );
}

/// [SettingEntity] entity fields to define ObjectBox queries.
class SettingEntity_ {
  /// See [SettingEntity.id].
  static final id = obx.QueryIntegerProperty<SettingEntity>(
    _entities[3].properties[0],
  );

  /// See [SettingEntity.key].
  static final key = obx.QueryStringProperty<SettingEntity>(
    _entities[3].properties[1],
  );

  /// See [SettingEntity.value].
  static final value = obx.QueryStringProperty<SettingEntity>(
    _entities[3].properties[2],
  );
}

/// [UserProfileEntity] entity fields to define ObjectBox queries.
class UserProfileEntity_ {
  /// See [UserProfileEntity.id].
  static final id = obx.QueryIntegerProperty<UserProfileEntity>(
    _entities[4].properties[0],
  );

  /// See [UserProfileEntity.userId].
  static final userId = obx.QueryStringProperty<UserProfileEntity>(
    _entities[4].properties[1],
  );

  /// See [UserProfileEntity.name].
  static final name = obx.QueryStringProperty<UserProfileEntity>(
    _entities[4].properties[2],
  );

  /// See [UserProfileEntity.email].
  static final email = obx.QueryStringProperty<UserProfileEntity>(
    _entities[4].properties[3],
  );

  /// See [UserProfileEntity.phone].
  static final phone = obx.QueryStringProperty<UserProfileEntity>(
    _entities[4].properties[4],
  );

  /// See [UserProfileEntity.birthDate].
  static final birthDate = obx.QueryStringProperty<UserProfileEntity>(
    _entities[4].properties[5],
  );
}
